package tests

// Odin compiles each directory as a separate package. Keep the application in
// src/ while exposing the implementation surface exercised by these white-box
// tests under the same unqualified names used throughout the test suite.
import app "../src"
import shared "../src/shared"

Animation_Playback :: shared.Animation_Playback
App_UI_Command_Context :: app.App_UI_Command_Context
CEL_STYLE_PRESET_PATHS := app.CEL_STYLE_PRESET_PATHS
Camera_Mouse_Drag :: app.Camera_Mouse_Drag
Capture_Options :: shared.Capture_Options
Capture_Parse_Error :: shared.Capture_Parse_Error
Capture_Target :: shared.Capture_Target
Capture_View :: shared.Capture_View
Cel_Style :: shared.Cel_Style
Cel_Style_Error :: shared.Cel_Style_Error
Cel_Style_UI_State :: app.Cel_Style_UI_State
DEFAULT_DOWNSCALE_LEVEL :: app.DEFAULT_DOWNSCALE_LEVEL
DEFAULT_LENS_SIZE :: app.DEFAULT_LENS_SIZE
Edge_AA_Mode :: shared.Edge_AA_Mode
GAME_CAMERA_FOVY :: app.GAME_CAMERA_FOVY
GAME_CAMERA_LOOK_AHEAD :: app.GAME_CAMERA_LOOK_AHEAD
GAME_DASH_DISTANCE :: app.GAME_DASH_DISTANCE
GAME_EXITS := app.GAME_EXITS
GAME_FIXED_DT :: app.GAME_FIXED_DT
GAME_MOVE_SPEED :: app.GAME_MOVE_SPEED
GAME_OCCLUSION_DEBUG_TINT :: app.GAME_OCCLUSION_DEBUG_TINT
GAME_OCCLUSION_DITHER_VISIBILITY :: app.GAME_OCCLUSION_DITHER_VISIBILITY
GAME_OCCLUSION_TEST_TREE :: app.GAME_OCCLUSION_TEST_TREE
GAME_OVERLOOK_POSITION :: app.GAME_OVERLOOK_POSITION
GAME_PIXEL_HEIGHT :: app.GAME_PIXEL_HEIGHT
GAME_PIXEL_WIDTH :: app.GAME_PIXEL_WIDTH
GAME_PLAYER_ANIMATION_SAMPLE_COUNT :: app.GAME_PLAYER_ANIMATION_SAMPLE_COUNT
GAME_PLAYER_RADIUS :: app.GAME_PLAYER_RADIUS
GAME_REPLAY_SCHEMA_VERSION :: app.GAME_REPLAY_SCHEMA_VERSION
GAME_ROOMS := app.GAME_ROOMS
GAME_SCREEN_HEIGHT :: app.GAME_SCREEN_HEIGHT
GAME_SCREEN_WIDTH :: app.GAME_SCREEN_WIDTH
GAME_ZOMBIE_ATTACK_ANIMATION :: app.GAME_ZOMBIE_ATTACK_ANIMATION
GAME_ZOMBIE_CHASE_SPEED :: app.GAME_ZOMBIE_CHASE_SPEED
GAME_ZOMBIE_COUNT :: app.GAME_ZOMBIE_COUNT
GAME_ZOMBIE_IDLE_ANIMATION :: app.GAME_ZOMBIE_IDLE_ANIMATION
GAME_ZOMBIE_MEMORY :: app.GAME_ZOMBIE_MEMORY
GAME_ZOMBIE_MODEL_PATH :: app.GAME_ZOMBIE_MODEL_PATH
GAME_ZOMBIE_RADIUS :: app.GAME_ZOMBIE_RADIUS
GAME_ZOMBIE_RETURN_RADIUS :: app.GAME_ZOMBIE_RETURN_RADIUS
GAME_ZOMBIE_SEPARATION :: app.GAME_ZOMBIE_SEPARATION
GAME_ZOMBIE_SPAWNS := app.GAME_ZOMBIE_SPAWNS
GAME_ZOMBIE_WALK_ANIMATION :: app.GAME_ZOMBIE_WALK_ANIMATION
GAME_ZOMBIE_WINDUP_TIME :: app.GAME_ZOMBIE_WINDUP_TIME
GLTF_SKIN_SCALE_EPSILON :: app.GLTF_SKIN_SCALE_EPSILON
Game_Assets :: app.Game_Assets
Game_Camera_State :: app.Game_Camera_State
Game_Decor_Kind :: app.Game_Decor_Kind
Game_Decor_Occlusion_Query :: app.Game_Decor_Occlusion_Query
Game_Decor_Visibility_Effect :: app.Game_Decor_Visibility_Effect
Game_Input :: app.Game_Input
Game_Movement_Tuning :: app.Game_Movement_Tuning
Game_Player_Mode :: app.Game_Player_Mode
Game_Replay_Error :: app.Game_Replay_Error
Game_Replay_File :: app.Game_Replay_File
Game_Replay_File_Segment :: app.Game_Replay_File_Segment
Game_Replay_Player :: app.Game_Replay_Player
Game_Replay_Stats :: app.Game_Replay_Stats
Game_Room_ID :: shared.Game_Room_ID
Game_Run_Options :: shared.Game_Run_Options
Game_Screen_Bounds :: app.Game_Screen_Bounds
Game_State :: app.Game_State
Game_Video_Options_Error :: shared.Game_Video_Options_Error
Game_Zombie_Animation_Kind :: app.Game_Zombie_Animation_Kind
Game_Zombie_Mode :: app.Game_Zombie_Mode
INSPECTOR_SECTION_HEADER_HEIGHT :: app.INSPECTOR_SECTION_HEADER_HEIGHT
Inspector_UI_State :: app.Inspector_UI_State
Lens_Mode :: shared.Lens_Mode
lens_mode_replaces_scene :: app.lens_mode_replaces_scene
MAX_CEL_BANDS :: shared.MAX_CEL_BANDS
MAX_DOWNSCALE_LEVEL :: app.MAX_DOWNSCALE_LEVEL
MIN_DOWNSCALE_LEVEL :: app.MIN_DOWNSCALE_LEVEL
MIN_LENS_SIZE :: app.MIN_LENS_SIZE
Model_Assets :: shared.Model_Assets
Model_Browser_State :: shared.Model_Browser_State
Model_Source_Kind :: shared.Model_Source_Kind
SCENE_DEFAULT_SHADOW_BIAS :: shared.SCENE_DEFAULT_SHADOW_BIAS
SCENE_DEFAULT_SHADOW_EXTENT :: shared.SCENE_DEFAULT_SHADOW_EXTENT
SCENE_DEFAULT_SHADOW_STRENGTH :: shared.SCENE_DEFAULT_SHADOW_STRENGTH
SCENE_MAX_LIGHT_INTENSITY :: shared.SCENE_MAX_LIGHT_INTENSITY
SCENE_MAX_POINT_LIGHTS :: shared.SCENE_MAX_POINT_LIGHTS
SCENE_MAX_SHADOW_BIAS :: shared.SCENE_MAX_SHADOW_BIAS
Scene_Animation_Pose :: shared.Scene_Animation_Pose
Scene_Editor_UI_State :: app.Scene_Editor_UI_State
Scene_Error :: shared.Scene_Error
Scene_Model :: shared.Scene_Model
Scene_Point_Light :: shared.Scene_Point_Light
Scene_Primitive :: shared.Scene_Primitive
Scene_Projection :: shared.Scene_Projection
Scene_Resources :: shared.Scene_Resources
Scene_Run_Options :: app.Scene_Run_Options
Scene_Spot_Light :: shared.Scene_Spot_Light
Scene_Transform :: shared.Scene_Transform
Scene_Video_Options_Error :: app.Scene_Video_Options_Error
UI_Focus_ID :: shared.UI_Focus_ID
UI_MOD_PRIMARY :: shared.UI_MOD_PRIMARY
UI_MOD_SHIFT :: shared.UI_MOD_SHIFT
UI_SHORTCUT_BINDINGS := shared.UI_SHORTCUT_BINDINGS
UI_Shortcut_Binding :: shared.UI_Shortcut_Binding
Viewer_Video_Options_Error :: app.Viewer_Video_Options_Error
add_cel_band_after :: app.add_cel_band_after
cel_ramp_pixels_build :: shared.cel_ramp_pixels_build
camera_input_permissions :: app.camera_input_permissions
camera_mouse_drag_for_frame :: app.camera_mouse_drag_for_frame
centered_lens_bounds :: app.centered_lens_bounds
cel_diffuse_to_band_index :: shared.cel_diffuse_to_band_index
cel_f32_is_finite :: shared.cel_f32_is_finite
cel_style_move_assign :: shared.cel_style_move_assign
cel_style_editor_height :: app.cel_style_editor_height
cli_argument_is_present :: shared.cli_argument_is_present
capture_options_destroy :: shared.capture_options_destroy
cel_style_destroy :: shared.cel_style_destroy
destroy_game_replay :: app.destroy_game_replay
model_assets_destroy :: shared.model_assets_destroy
model_browser_state_destroy :: shared.model_browser_state_destroy
scene_destroy :: shared.scene_destroy
scene_file_destroy :: shared.scene_file_destroy
capture_output_directory_ensure :: shared.capture_output_directory_ensure
Capture_Export_Error :: shared.Capture_Export_Error
execute_ui_command :: app.execute_ui_command
capture_find_model_source :: shared.capture_find_model_source
capture_sequence_output_path_format :: shared.capture_sequence_output_path_format
model_search_fuzzy_score :: shared.model_search_fuzzy_score
game_camera_round_pixel_coordinate :: app.game_camera_round_pixel_coordinate
game_configure_player_animation :: app.game_configure_player_animation
game_decor_occludes_player :: app.game_decor_occludes_player
game_decor_occlusion_query :: app.game_decor_occlusion_query
game_decor_visibility_amount :: app.game_decor_visibility_amount
game_decor_visibility_effect :: app.game_decor_visibility_effect
game_decor_visibility_tint :: app.game_decor_visibility_tint
game_default_movement_tuning :: app.game_default_movement_tuning
game_exit_boundary_position :: app.game_exit_boundary_position
game_fixed_update :: app.game_fixed_update
game_mode_requested :: app.game_mode_requested
game_normalize_input :: app.game_normalize_input
game_pixel_snap_offset :: app.game_pixel_snap_offset
lens_layout_max_size :: app.lens_layout_max_size
lens_resize_drag_for_frame :: app.lens_resize_drag_for_frame
lens_resize_handle_bounds :: app.lens_resize_handle_bounds
lens_resize_size_for_pointer :: app.lens_resize_size_for_pointer
game_position_hits_hazard :: app.game_position_hits_hazard
game_position_hits_obstacle :: app.game_position_hits_obstacle
game_position_inside_room :: app.game_position_inside_room
game_position_inside_room_radius :: app.game_position_inside_room_radius
game_replay_from_file :: app.game_replay_from_file
game_replay_next_input :: app.game_replay_next_input
game_replay_stats_observe_tick :: app.game_replay_stats_observe_tick
game_room :: app.game_room
game_screen_bounds_intersection :: app.game_screen_bounds_intersection
game_start_room_transition :: app.game_start_room_transition
game_state_init :: app.game_state_init
game_try_start_room_transition :: app.game_try_start_room_transition
game_update_camera :: app.game_update_camera
game_update_decor_visibility_flags :: app.game_update_decor_visibility_flags
game_update_progress :: app.game_update_progress
game_vector2_length :: shared.game_vector2_length
game_zombie_animation_kind :: app.game_zombie_animation_kind
game_zombie_can_see_player :: app.game_zombie_can_see_player
game_zombie_patrol_anchor :: app.game_zombie_patrol_anchor
game_zombie_position_blocked :: app.game_zombie_position_blocked
game_zombie_walk_towards :: app.game_zombie_walk_towards
animation_playback_pose_frame :: shared.animation_playback_pose_frame
animation_playback_select_clip :: shared.animation_playback_select_clip
render_downsample_dimension :: shared.render_downsample_dimension
gltf_find_skinned_mesh_uniform_scale :: shared.gltf_find_skinned_mesh_uniform_scale
matrix_find_pure_uniform_scale :: shared.matrix_find_pure_uniform_scale
cel_style_load :: shared.cel_style_load
load_game_replay :: app.load_game_replay
scene_load :: shared.scene_load
cel_style_make_classic :: shared.cel_style_make_classic
scene_make_default :: shared.scene_make_default
make_game_cel_style :: app.make_game_cel_style
capture_options_parse :: shared.capture_options_parse
parse_game_run_options :: app.parse_game_run_options
parse_scene_run_options :: app.parse_scene_run_options
model_search_results_rebuild :: shared.model_search_results_rebuild
remove_cel_band :: app.remove_cel_band
cel_style_save :: shared.cel_style_save
scene_save :: shared.scene_save
scene_add_primitive :: app.scene_add_primitive
scene_editor_delete_selection :: app.scene_editor_delete_selection
scene_editor_duplicate_selection :: app.scene_editor_duplicate_selection
scene_editor_ui_init :: app.scene_editor_ui_init
scene_file_path_is_portable :: shared.scene_file_path_is_portable
scene_from_file_data :: shared.scene_from_file_data
scene_shadow_frame_make :: shared.scene_shadow_frame_make
scene_to_file_data :: shared.scene_to_file_data
scene_transform_matrix :: shared.scene_transform_matrix
scene_video_duration_frame_count :: app.scene_video_duration_frame_count
scene_video_orbit_camera :: app.scene_video_orbit_camera
scene_video_orbit_degrees :: app.scene_video_orbit_degrees
cli_help_is_requested :: shared.cli_help_is_requested
ui_focus_fallback :: shared.ui_focus_fallback
ui_int_slider_quantize :: shared.ui_int_slider_quantize
ui_shortcut_modifiers_match :: shared.ui_shortcut_modifiers_match
cel_style_validate :: shared.cel_style_validate
game_video_options_validate :: shared.game_video_options_validate
scene_validate :: shared.scene_validate
validate_scene_capture_options :: app.validate_scene_capture_options
validate_scene_video_options :: app.validate_scene_video_options
validate_viewer_video_options :: app.validate_viewer_video_options
viewer_mode_requested :: app.viewer_mode_requested
video_stream_ffmpeg_command_build :: shared.video_stream_ffmpeg_command_build
video_stream_frame_byte_count :: shared.video_stream_frame_byte_count
video_stream_temporary_output_path :: shared.video_stream_temporary_output_path
viewer_video_expected_frame_count :: app.viewer_video_expected_frame_count
viewer_video_pose_frame :: app.viewer_video_pose_frame
